name: personalapp
version: 1.0.0+1
publish_to: 'none'
description: Futuristic minimal notes, reminders, and calendar tasks app.

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4

flutter:
  uses-material-design: true
